### ISSUE TITLE
Github link in help file points to bad URL

### ISSUE THREAD

**Issue by ghoetker** [asjadnaqvi/stata-alluvial#1]
The Stata .hlp file for v 1.0 (beta) points to https://github.com/asjadnaqvi/alluvial, rather than https://github.com/asjadnaqvi/stata-alluvial.  This is also true for your sankey program. Awesome contribution. Thanks.

**Comment by asjadnaqvi** [comment]
Ah thanks for finding this! I have patched the helpfile of both the packages on GitHub. With the next updates, will send it to SSC.
