### ISSUE TITLE
add option to control the gap between the value labels and the wedges

### ISSUE THREAD

**Issue by ericmelse** [asjadnaqvi/stata-alluvial#14]
The value labels are positioned tighly left of right of the wedges, like:
```
sysuse nlsw88.dta, clear
label define racelbl 3 ".    O", modify
alluvial race married collgrad smsa union, palette(CET C7) labs(*1.4) showtot boxw(*16) shares vals(*1.2) valf(%12.2f) 
```
which results in:
![Alluvial_test_1_20230418](https://user-images.githubusercontent.com/3686136/232673779-75f5dd32-efe1-4fba-bfa0-0487e9eac61d.png)
As such that is fine, but, to be able to control the gap would further enhance the visualization.
Possibly something like:
```
valgap(str)
The gap of the displayed values labels from the left or right side of the wedges. Default is labg(0) for no gap. 
```

**Comment by asjadnaqvi** [comment]
`valgap()` option is already there. Somehow it didn't make it in the help file. Will update it.
