### ISSUE TITLE
Show percentages %

### ISSUE THREAD

**Issue by MinZhang1987** [asjadnaqvi/stata-alluvial#19]
Hello,

Many thanks for the amazing graph package. I wonder if it's possible to show percentages%. For example, instead of 0.08, the labels may have the options to show 8.00%. 

Many thanks!

**Comment by ericmelse** [comment]
Plotting percentages in Stata graphics is a real challenge. Personally, I consider it the 'Achilles heel' of Stata. But, I agree that to have the choice between reporting fractions (percentages) like: 0.15 or .15 or 15% (and controlling decimals like 15.1% or 15.12%) is so very much 'standard functionality' that is bizar that we have to resort to 'heavy lifted coding' to get such things done in Stata. Especially rounding fraction results for percentages is most awkward.
Asjad, I have my own 'crude' solutions that I could share for inspiration should you have to start from scratch for this.

**Comment by asjadnaqvi** [comment]
added in v1.4
