### ISSUE TITLE
Alluvial chart shows errors!

### ISSUE THREAD

**Issue by datalake101** [asjadnaqvi/stata-alluvial#2]
. sysuse nlsw88.dta, clear
(NLSW, 1988 extract)

. alluvial race married collgrad smsa union
race has more than 20 categories. The variable might be continuous.
Please simplify or drop the variable.
married has more than 20 categories. The variable might be continuous.
Please simplify or drop the variable.
collgrad has more than 20 categories. The variable might be continuous.
Please simplify or drop the variable.
smsa has more than 20 categories. The variable might be continuous.
Please simplify or drop the variable.
union has more than 20 categories. The variable might be continuous.
Please simplify or drop the variable.

**Comment by asjadnaqvi** [comment]
I just checked on a new computer and I am not getting this error. Which version of Stata do you have?

It might have to do with `levelsof` not returning a `r(r)` option in earlier versions.

**Comment by asjadnaqvi** [comment]
@datalake101 is this issue still relevant?
