### ISSUE TITLE
from() variable wrongly gets the to() labels when originally numeric

### ISSUE THREAD

**Issue by ianrwhite** [asjadnaqvi/stata-alluvial#21]
See e.g. the result of this:

use "https://www.stata-press.com/data/r18/nhanes2l.dta", clear
egen tcgrp = cut(tcresult), group(3) label
gen n=1
sankey n, from(agegrp) to(tcgrp) by(sex)

**Comment by asjadnaqvi** [comment]
Fixed in v1.71. Installation:
```
net install sankey, from("https://raw.githubusercontent.com/asjadnaqvi/stata-sankey/main/installation/") replace
```

More info on https://github.com/asjadnaqvi/stata-sankey. This is the repository of the alluvial package. 

![bugfix](https://github.com/asjadnaqvi/stata-alluvial/assets/38498046/0e363290-f251-4a14-9684-b2fc2b280d81)
