### ISSUE TITLE
Alluvial flows with gradient colors

### ISSUE THREAD

**Issue by ericmelse** [asjadnaqvi/stata-alluvial#25]
Dear Asjad,
When I remember it correctly, I think that you have 'grumbled' at a Stata meeting about the lack of functionality in the Stata graphics engine to define gradient colors between graphical parts, so that we could use that for Alluvial or Sankey flows with gradient colors, like:
![Alluvial flows with gradient colors](https://github.com/user-attachments/assets/3638ffce-7a79-406a-a7cb-c84012bdf261)
(snapshotted from [here](https://www.sankeyjourney.com/))

If so, is there any hope for us that this is going to be made possible?
If not, should I write Stata Technical Support about this need?
Best,
Eric

**Comment by asjadnaqvi** [comment]
Dear Eric, certainly gradients would be good and we did discuss this a couple of time but most likely such a feature low on the priority list. Especially given that there are a lot more trivial fixes that can be done, such as placing legends outside of the fixed clock positions, or reading colors, line widths from variables to avoid very large loops and so on.

It is also mentioned in the wishlist post in the forum.

**Comment by ericmelse** [comment]
Dear Asjad, thank you for your explanation. I have found the Stata 19 wishlist post and 'liked' the request ([#3](https://www.statalist.org/forums/forum/general-stata-discussion/general/1711202-wishlist-for-stata-19) !). Certainly the other alluvial fixes are of interest as well, so, I will wait patiently for the gradient colors to appear.

**Comment by ericmelse** [comment]
Dear Asjad,

I went one step further an [posted this](https://www.statalist.org/forums/forum/general-stata-discussion/general/1711202-wishlist-for-stata-19/page25) on the Stata 19 wishlist (# 369).
