### ISSUE TITLE
The format of the displayed values

### ISSUE THREAD

**Issue by ericmelse** [asjadnaqvi/stata-alluvial#27]
Dear Asjad,

I try to control the format of the displayed values in the alluvial plot.
Maybe I do something wrong now, but I use this code:
```
sysuse nlsw88.dta, clear
alluvial race married collgrad smsa union, valf(%12.0f)
```
which is nothing other than the default that is used (according to the help file), but, this code returns the error:
```
option valformat() not allowed
r(198);
```
What I really try to accomplish is to control the number of decimals when the option `percent` is used, like:
`
alluvial race married collgrad smsa union, percent
`
to any number other than two decimals.

Your helping hand is appreciated very much.

**Comment by asjadnaqvi** [comment]
It is now just `format()`. I corrected the help file. 

This is what happens when several packages are updated at the same time...

**Comment by ericmelse** [comment]
Yes! Perfect is!
