### ISSUE TITLE
[if] restriction of dataset

### ISSUE THREAD

**Issue by BorisWieczorek** [asjadnaqvi/stata-alluvial#29]
Good morning, 
I am pleased to discover your alluvial package on Stata with this latest version, v1.41 (downloaded on 15/11/2024—today).
Unfortunately, I noticed that the restriction of the dataset with "if" does not work. 
Of course, a temporary solution is to drop observations that do not meet the desired characteristics. But I wanted to pass on the information. 
Thank you for your work.
Boris Wieczorek

PS: I am using Stata/SE 18.0, and I installed the package as described in the ReadMe:
net install alluvial, from("https://raw.githubusercontent.com/asjadnaqvi/stata-alluvial/main/installation/") replace
ssc install palettes, replace
ssc install colrspace, replace
ado update, update
ssc install schemepack, replace
set scheme white_tableau
graph set window fontface "Arial Narrow"

**Comment by asjadnaqvi** [comment]
Thank you for spotting this! Fixed it in the latest patch.
